mode: local
server:
  port: 3846

  cors:
    allowedOrigins:
      - "http://localhost:3000"
    allowedMethods:
      - "OPTIONS"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    allowedHeaders:
      - "Content-Type"
      - "Authorization"
    exposedHeaders:
      - "Authorization"
    allowCredentials: true
    maxAge: 3600

  session:
    secret: secret

db:
  mode: postgres # postgres, sqlite3
  dsn: host=localhost user=root password=password dbname=idp_db port=5432 sslmode=disable TimeZone=Asia/Tokyo

webauthn:
  displayName: "go-idp"
  rpId: "localhost"
  rpOrigins:
    - "http://localhost:3000"
    - "http://localhost:3846"
