version: "3.9"

services:
  idp_db:
    image: postgres:16
    container_name: idp_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=idp_db
    volumes:
      - idp_db_vol:/var/lib/postgresql/data

volumes:
  idp_db_vol:
