openapi: 3.0.0
info:
  description: Go-IdP
  title: Go-IdP
  version: 1.0.0
servers:
- description: ローカル環境
  url: http://localhost:3846
paths:
  /api/v1/webauthn/start:
    get:
      description: WebAuthn 登録開始
      operationId: webauthnStart
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebAuthnStartResponse'
          description: WebAuthn 登録開始
      security:
      - Bearer: []
      summary: 登録開始
      tags:
      - webauthn
components:
  schemas:
    WebAuthnStartResponse:
      example:
        extensions:
          appid: https://example.com
          exts: true
          authnSel: required
        attestation: none
        challenge: R_g3M58WQWSas4mjL2SVKg
        authenticatorSelection:
          authenticatorAttachment: cross-platform
          userVerification: required
          requireResidentKey: false
        user:
          displayName: John Doe
          name: John Doe
          id: "1234567890"
        rp:
          name: Example
          id: example.com
        timeout: 60000
        excludeCredentials:
        - id: "1234567890"
          type: public-key
        - id: "1234567890"
          type: public-key
        pubKeyCredParams:
        - type: public-key
          alg: -7
        - type: public-key
          alg: -7
      properties:
        rp:
          $ref: '#/components/schemas/WebAuthnStartResponse_rp'
        user:
          $ref: '#/components/schemas/WebAuthnStartResponse_user'
        challenge:
          example: R_g3M58WQWSas4mjL2SVKg
          type: string
        pubKeyCredParams:
          items:
            $ref: '#/components/schemas/WebAuthnStartResponse_pubKeyCredParams_inner'
          type: array
        timeout:
          example: 60000
          type: integer
        excludeCredentials:
          items:
            $ref: '#/components/schemas/WebAuthnStartResponse_excludeCredentials_inner'
          type: array
        authenticatorSelection:
          $ref: '#/components/schemas/WebAuthnStartResponse_authenticatorSelection'
        attestation:
          example: none
          type: string
        extensions:
          $ref: '#/components/schemas/WebAuthnStartResponse_extensions'
      required:
      - attestation
      - authenticatorSelection
      - challenge
      - excludeCredentials
      - pubKeyCredParams
      - rp
      - timeout
      - user
      type: object
    WebAuthnStartResponse_rp:
      example:
        name: Example
        id: example.com
      properties:
        id:
          example: example.com
          type: string
        name:
          example: Example
          type: string
      type: object
    WebAuthnStartResponse_user:
      example:
        displayName: John Doe
        name: John Doe
        id: "1234567890"
      properties:
        id:
          example: "1234567890"
          type: string
        name:
          example: John Doe
          type: string
        displayName:
          example: John Doe
          type: string
      type: object
    WebAuthnStartResponse_pubKeyCredParams_inner:
      example:
        type: public-key
        alg: -7
      properties:
        alg:
          example: -7
          format: int64
          type: integer
        type:
          example: public-key
          type: string
      type: object
    WebAuthnStartResponse_excludeCredentials_inner:
      example:
        id: "1234567890"
        type: public-key
      properties:
        id:
          example: "1234567890"
          type: string
        type:
          example: public-key
          type: string
      type: object
    WebAuthnStartResponse_authenticatorSelection:
      example:
        authenticatorAttachment: cross-platform
        userVerification: required
        requireResidentKey: false
      properties:
        authenticatorAttachment:
          example: cross-platform
          type: string
        requireResidentKey:
          example: false
          type: boolean
        userVerification:
          example: required
          type: string
      type: object
    WebAuthnStartResponse_extensions:
      example:
        appid: https://example.com
        exts: true
        authnSel: required
      properties:
        appid:
          example: https://example.com
          type: string
        authnSel:
          example: required
          type: string
        exts:
          example: true
          type: boolean
      type: object
  securitySchemes:
    Bearer:
      description: アクセストークンを設定します
      scheme: bearer
      type: http
