openapi: 3.0.0
info:
  description: Go-IdP
  title: Go-IdP
  version: 1.0.0
servers:
- description: ローカル環境
  url: http://localhost:3846
paths:
  /admin/clients:
    post:
      description: clientの登録を行います
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
          description: Client登録成功
      summary: client登録
      tags:
      - client
components:
  schemas:
    ClientRequest:
      example:
        grant_types:
        - authorization_code
        - refresh_token
        - client_credentials
        client_secret: "1234567890"
        redirect_uris:
        - https://example.com/callback
        - https://example.com/callback
        scopes:
        - openid
        - profile
        client_id: "1234567890"
        response_types:
        - code
        - token
        - id_token token
      properties:
        client_id:
          description: クライアントID
          example: "1234567890"
          type: string
        client_secret:
          description: クライアントシークレット
          example: "1234567890"
          type: string
        redirect_uris:
          items:
            description: リダイレクトURI
            example: https://example.com/callback
            type: string
          type: array
        grant_types:
          example:
          - authorization_code
          - refresh_token
          - client_credentials
          items:
            description: クライアントがサポートする認可タイプ
            type: string
          type: array
        response_types:
          example:
          - code
          - token
          - id_token token
          items:
            description: レスポンスタイプ
            type: string
          type: array
        scopes:
          description: |
            クライアントがサポートするスコープ
            - openid: OpenID Connectのスコープ
            - offline: リフレッシュトークンを取得するためのスコープ
          example:
          - openid
          - profile
          items:
            enum:
            - openid
            - offline
            type: string
          type: array
      required:
      - client_id
      - client_secret
      - grant_types
      - redirect_uris
      - response_types
      - scopes
      type: object
    ClientResponse:
      example:
        grant_types:
        - authorization_code
        - refresh_token
        - client_credentials
        redirect_uris:
        - https://example.com/callback
        - https://example.com/callback
        scopes:
        - openid
        - profile
        client_id: "1234567890"
        response_types:
        - code
        - token
        - id_token token
      properties:
        client_id:
          description: クライアントID
          example: "1234567890"
          type: string
        redirect_uris:
          items:
            description: リダイレクトURI
            example: https://example.com/callback
            type: string
          type: array
        grant_types:
          example:
          - authorization_code
          - refresh_token
          - client_credentials
          items:
            description: クライアントがサポートする認可タイプ
            type: string
          type: array
        response_types:
          example:
          - code
          - token
          - id_token token
          items:
            description: レスポンスタイプ
            type: string
          type: array
        scopes:
          description: |
            クライアントがサポートするスコープ
            - openid: OpenID Connectのスコープ
            - offline: リフレッシュトークンを取得するためのスコープ
          example:
          - openid
          - profile
          items:
            enum:
            - openid
            - offline
            type: string
          type: array
      required:
      - client_id
      - grant_types
      - redirect_uris
      - response_types
      - scopes
      type: object
    client_id:
      description: クライアントID
      example: "1234567890"
      type: string
    client_secret:
      description: クライアントシークレット
      example: "1234567890"
      type: string
    redirect_uris:
      items:
        description: リダイレクトURI
        example: https://example.com/callback
        type: string
      type: array
    grant_types:
      example:
      - authorization_code
      - refresh_token
      - client_credentials
      items:
        description: クライアントがサポートする認可タイプ
        type: string
      type: array
    response_types:
      example:
      - code
      - token
      - id_token token
      items:
        description: レスポンスタイプ
        type: string
      type: array
    scopes:
      description: |
        クライアントがサポートするスコープ
        - openid: OpenID Connectのスコープ
        - offline: リフレッシュトークンを取得するためのスコープ
      example:
      - openid
      - profile
      items:
        enum:
        - openid
        - offline
        type: string
      type: array
  securitySchemes:
    Bearer:
      description: アクセストークンを設定します
      scheme: bearer
      type: http
