openapi: 3.0.0

info:
  version: 1.0.0
  title: Go-IdP
  description: Go-IdP

servers:
  - url: http://localhost:3846
    description: ローカル環境

paths:
  /api/v1/webauthn/start:
    $ref: './paths/resources/webauthn/start.yml'

components: 
  securitySchemes:
    Bearer:
      $ref: './components/security/bearerAuth.yml'